services:
  # Backend API Service
  - type: web
    name: filmila
    env: node
    rootDirectory: backend
    buildCommand: |
      echo "Current directory: $PWD"
      ls -la
      cd ../frontend && npm ci --production=false && npm run build
      cd ../backend
      ls -la
      mkdir -p frontend/build
      cp -r ../frontend/build/* frontend/build/
      ls -la frontend/build
      npm ci --production=false && npm run build && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: filmila-db
          property: connectionString
      - key: DATABASE_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 24h
      - key: FRONTEND_URL
        value: https://filmila-web.onrender.com
      - key: API_PREFIX
        value: /api
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_S3_BUCKET
        value: filmila-videos
      - key: CLOUDFRONT_DOMAIN
        value: d1k0enfou8eft6.cloudfront.net

  # Frontend Static Site
  - type: web
    name: filmila-web
    env: static
    rootDir: frontend
    buildCommand: |
      npm ci --production=false
      npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://filmila-api.onrender.com/api
      - key: REACT_APP_CLOUDFRONT_DOMAIN
        value: d1k0enfou8eft6.cloudfront.net
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: filmila-db
    plan: free
    ipAllowList: []
