services:
  # Backend API Service
  - type: web
    name: filmila
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory: $PWD"
      ls -la
      
      echo "\nBuilding frontend..."
      cd frontend
      echo "Frontend directory: $PWD"
      ls -la
      npm ci --production=false
      CI=false npm run build
      echo "Frontend build complete. Build directory contents:"
      ls -la build
      
      echo "\nPreparing backend..."
      cd ../backend
      echo "Backend directory: $PWD"
      ls -la
      
      echo "\nInstalling backend dependencies..."
      npm ci --production=false
      npm run build
      npm run migrate
      
      echo "\nCreating public directory..."
      mkdir -p public
      echo "Copying frontend build..."
      cp -rv ../frontend/build/* public/
      echo "Frontend build copied. Contents of public directory:"
      ls -la public
      
      echo "\nFinal directory structure:"
      pwd
      echo "Current directory contents:"
      ls -la
      echo "Public directory contents:"
      ls -la public
    startCommand: |
      echo "Starting server from directory:"
      pwd
      ls -la
      echo "\nPublic directory contents:"
      ls -la public
      node dist/app.js
    rootDirectory: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: filmila-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 24h
      - key: FRONTEND_URL
        value: https://filmila-web.onrender.com
      - key: API_PREFIX
        value: /api
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_S3_BUCKET
        value: filmila-videos
      - key: CLOUDFRONT_DOMAIN
        value: d1k0enfou8eft6.cloudfront.net

  # Frontend Static Site
  - type: web
    name: filmila-web
    env: static
    rootDir: frontend
    buildCommand: |
      npm ci --production=false
      npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://filmila-api.onrender.com/api
      - key: REACT_APP_CLOUDFRONT_DOMAIN
        value: d1k0enfou8eft6.cloudfront.net
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: filmila-db
    plan: free
    ipAllowList: []
