services:
  # Combined Backend and Frontend Service
  - type: web
    name: filmila
    env: node
    nodeVersion: 18.x
    buildCommand: |
      npm install
      cd frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: cd backend && npm start
    rootDirectory: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: true
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY
        value: 24h
      - key: FRONTEND_URL
        value: https://filmila.onrender.com
      - key: API_PREFIX
        value: /api
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: eu-north-1
      - key: AWS_S3_BUCKET
        value: filmila-videos
      - key: CLOUDFRONT_DOMAIN
        value: d1k0enfou8eft6.cloudfront.net
      - key: REACT_APP_API_URL
        value: https://filmila.onrender.com/api
      - key: REACT_APP_CLOUDFRONT_DOMAIN
        value: d1k0enfou8eft6.cloudfront.net

databases:
  - name: filmila_db
    databaseName: filmila_db
    user: filmila_db_user
    plan: free
    ipAllowList: []
